// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ChatMessageTmp.proto

package proto_gen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessage struct {
	Message              *string  `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	Time                 *int64   `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	ChatPerson           *string  `protobuf:"bytes,3,req,name=chatPerson" json:"chatPerson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_396bc822d6ae0d75, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ChatMessage) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *ChatMessage) GetChatPerson() string {
	if m != nil && m.ChatPerson != nil {
		return *m.ChatPerson
	}
	return ""
}

type ChatMessageList struct {
	ChatMessages         []*ChatMessage `protobuf:"bytes,1,rep,name=chatMessages" json:"chatMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChatMessageList) Reset()         { *m = ChatMessageList{} }
func (m *ChatMessageList) String() string { return proto.CompactTextString(m) }
func (*ChatMessageList) ProtoMessage()    {}
func (*ChatMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_396bc822d6ae0d75, []int{1}
}

func (m *ChatMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageList.Unmarshal(m, b)
}
func (m *ChatMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageList.Marshal(b, m, deterministic)
}
func (m *ChatMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageList.Merge(m, src)
}
func (m *ChatMessageList) XXX_Size() int {
	return xxx_messageInfo_ChatMessageList.Size(m)
}
func (m *ChatMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageList proto.InternalMessageInfo

func (m *ChatMessageList) GetChatMessages() []*ChatMessage {
	if m != nil {
		return m.ChatMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "proto_gen.ChatMessage")
	proto.RegisterType((*ChatMessageList)(nil), "proto_gen.ChatMessageList")
}

func init() { proto.RegisterFile("proto/ChatMessageTmp.proto", fileDescriptor_396bc822d6ae0d75) }

var fileDescriptor_396bc822d6ae0d75 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0xce, 0x48, 0x2c, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0xc9, 0x2d,
	0xd0, 0x03, 0x0b, 0x0a, 0x71, 0x82, 0xa9, 0xf8, 0xf4, 0xd4, 0x3c, 0xa5, 0x68, 0x2e, 0x6e, 0x24,
	0x25, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0x10, 0xa6, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x67, 0x10, 0x8c,
	0x2b, 0x24, 0xc4, 0xc5, 0x52, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa4, 0xc1, 0x1c, 0x04,
	0x66, 0x0b, 0xc9, 0x71, 0x71, 0x25, 0x67, 0x24, 0x96, 0x04, 0xa4, 0x16, 0x15, 0xe7, 0xe7, 0x49,
	0x30, 0x83, 0x35, 0x20, 0x89, 0x28, 0xf9, 0x72, 0xf1, 0x23, 0x19, 0xee, 0x93, 0x59, 0x5c, 0x22,
	0x64, 0xc5, 0xc5, 0x93, 0x8c, 0x10, 0x2a, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd3,
	0x83, 0xbb, 0x48, 0x0f, 0x49, 0x47, 0x10, 0x8a, 0x5a, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41,
	0xab, 0x46, 0x8b, 0xd3, 0x00, 0x00, 0x00,
}
